language: python
python:
  - "2.7"
cache:
  - pip
install:
  - sudo apt-get install toilet
  - pip install petlib
branches:
  only:
    - master
script:
  - python -m pytest -v Lab*/Lab*Tests.py
after_failure:
  - toilet --gay "Rekt."
after_success:
  - toilet --gay "Wheeeey!"
